# -*- coding: utf-8 -*-
"""Data_Integration_and _model_ building_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTBz_iIVYkZkhDcsJgNdnraNd_Qs92me

**Partie 5:**  Data Integration and model building

L’objectif est de construire le **moteur de matching intelligent de SCORE CV AI**.
Cette étape fusionne les informations **NER, relations, compétences et TF-IDF** pour comparer un CV aux offres d’emploi.
Nous allons **regrouper `score_cv_ai_model.py` et `scoring.py` dans un même Colab** : **Data Integration and Model Building**.
Le modèle calculera un **score hybride pondéré**, puis classera les offres selon leur pertinence.
Enfin, **JSearch API** permettra de récupérer les offres et de générer un **Top 10 personnalisé**.
"""

# -*- coding: utf-8 -*-

# ============================================================
# INSTALLATIONS
# ============================================================

!pip install -q requests spacy scikit-learn nltk pandas numpy

# ============================================================
# IMPORTS DES BIBLIOTHEQUES
# ============================================================

import os
import json
import logging
import requests

from datetime import datetime
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ============================================================
# CONFIGURATION LOGGER
# ============================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger(__name__)

import os
from google.colab import userdata
os.environ["RAPIDAPI_KEY"] = userdata.get('RAPIDAPI_KEY') # Utilisation de la clé RapidAPI réelle de userdata

from google.colab import userdata
userdata.get('RAPIDAPI_KEY')

# ============================================================
# ÉTAPE 1 : CV DATA INTEGRATOR
# ============================================================

class CVDataIntegrator:
    """
    Intègre le texte nettoyé, les entités NER et les relations
    dans un profil candidat structuré.

    RESPONSABILITÉS :

    - Stocker le texte nettoyé
    - Organiser les entités
    - Extraire les compétences
    - Conserver les relations
    - Construire le texte destiné au matching
    """

    def __init__(self):
        """Initialise l'intégrateur."""

        logger.info(" CVDataIntegrator initialized")

    def integrate(
        self,
        cleaned_text: str,
        entities: List[Dict[str, Any]],
        relationships: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Fusionne les données du CV dans un profil structuré.

        Args:
            cleaned_text:
                Texte nettoyé du CV.

            entities:
                Entités NER extraites du CV.

            relationships:
                Relations extraites du CV.

        Returns:
            Profil candidat structuré.
        """

        logger.info(" Integrating candidate data...")

        cleaned_text = cleaned_text or ""
        entities = entities or []
        relationships = relationships or []

        # ======================================================
        # EXTRACTION DES SKILLS
        # ======================================================

        skills = []

        for entity in entities:

                if not isinstance(entity, dict):
                    continue

                label = str(
                    entity.get("label", "")
                ).upper()

                text = (
                    entity.get("text")
                    or entity.get("target")
                    or ""
                )

                if label in ["SKILL", "CERTIFICATION"] and text:

                    skills.append(str(text).strip())

        # =================================================
        # DÉDUPLICATION DES SKILLS
        # ==================================================

        unique_skills = list(
            dict.fromkeys(
                skill
                for skill in skills
                if skill
            )
        )

        # ====================================================
        # GROUPEMENT DES ENTITÉS
        # ====================================================

        entities_by_type = {}

        for entity in entities:

            if not isinstance(entity, dict):
                continue

            entity_type = (
                entity.get("label")
                or "UNKNOWN"
            )

            entity_text = (
                entity.get("text")
                or ""
            )

            if entity_type not in entities_by_type:

                entities_by_type[entity_type] = []

            if entity_text:

                entities_by_type[entity_type].append(
                    entity_text
                )

        # =====================================================
        # PROFIL CANDIDAT
        # ====================================================

        profile = {

                    "text": cleaned_text,

                    "entities": entities,

                    "relationships": relationships,

                    "skills": unique_skills,

                    "entities_by_type": entities_by_type,

                    "num_entities": len(entities),

                    "num_skills": len(unique_skills),

                    "num_relationships": len(relationships)
                }

        logger.info(
                    f" Profile created | "
                    f"Entities: {profile['num_entities']} | "
                    f"Skills: {profile['num_skills']} | "
                    f"Relations: {profile['num_relationships']}"
                )

        return profile

    # ========================================================
    # CONSTRUCTION DU TEXTE DE MATCHING
    # ========================================================

    def build_matching_text(
            self,
            profile: Dict[str, Any]
        ) -> str:
            """
            Construit le texte utilisé pour le matching TF-IDF.

            Combine :

            - texte du CV
            - texte des entités
            - skills

            Returns:
                Texte complet de matching.
            """

            text = profile.get(
                "text",
                ""
            )

            entities = profile.get(
                "entities",
                []
            )

            skills = profile.get(
                "skills",
                []
            )

            # =====================================================
            # TEXTE DES ENTITÉS
            # =====================================================

            entity_texts = []

            for entity in entities:

                if not isinstance(entity, dict):
                    continue

                entity_text = (
                    entity.get("text")
                    or ""
                )

                if entity_text:

                    entity_texts.append(
                        str(entity_text)
                    )

            # ========================================================
            # COMBINAISON
            # ========================================================

            all_parts = [

                text,

                " ".join(entity_texts),

                " ".join(skills)

            ]

            matching_text = " ".join(
                part.strip()
                for part in all_parts
                if part
            )

            logger.info(
                f" Matching text built | "
                f"Length: {len(matching_text)} chars"
            )

            return matching_text.strip()

# ============================================================
# ÉTAPE 2 : TF-IDF MATCHER
# ============================================================

class TfidfMatcher:
    """
    Calcule la similarité entre le CV et une offre
    grâce à TF-IDF + cosine similarity.

    TF-IDF :
        Term Frequency - Inverse Document Frequency

    Similarité :
        Cosine Similarity

    Score :
        0 = aucune similarité
        1 = similarité maximale
    """

    def __init__(self):
        """
        Initialise le vectorizer.
        """

        logger.info(
            " TfidfMatcher initialized"
        )

        # Correction : max_df=1.0 pour ne pas filtrer les mots
        # communs lorsque l'on compare 2 documents.
        self.vectorizer = TfidfVectorizer(

            max_features=5000,

            min_df=1,

            max_df=1.0,

            ngram_range=(1, 2),

            lowercase=True,

            sublinear_tf=True
        )

# ========================================================
    # CALCUL SIMILARITÉ
    # ========================================================

    def calculate_similarity(
        self,
        cv_text: str,
        job_text: str
    ) -> float:
        """
        Calcule la similarité cosinus TF-IDF.

        Args:
            cv_text:
                Texte du CV.

            job_text:
                Description du job.

        Returns:
            Score entre 0 et 1.
        """

        logger.info(
            " Calculating TF-IDF similarity..."
        )

        # ====================================================
        # SÉCURISATION
        # ====================================================

        if not cv_text or not job_text:

            logger.warning(
                " Empty text provided"
            )

            return 0.0

        try:

            # =================================================
            # VECTORISATION
            # ================================================

            vectors = self.vectorizer.fit_transform(
                [
                    str(cv_text),
                    str(job_text)
                ]
            )

            # =================================================
            # SIMILARITÉ COSINUS
            # =================================================

            similarity = cosine_similarity(
                vectors[0:1],
                vectors[1:2]
            )[0][0]

            score = float(
                np.clip(
                    similarity,
                    0.0,
                    1.0
                )
            )

            logger.info(
                f"TF-IDF Score: {score:.3f}"
            )

            return round(
                score,
                3
            )

        except Exception as e:

            logger.error(
                f" TF-IDF Error: {e}"
            )

            return 0.0

# ============================================================
# ÉTAPE 3 : JSEARCH CLIENT
# ============================================================

class JSearchClient:
    """
    Client réel JSearch via RapidAPI.

    RESPONSABILITÉS :

    - Authentification RapidAPI
    - Recherche d'offres réelles
    - Gestion des erreurs HTTP
    - Transformation des données JSearch
    - Préparation des offres pour SCORE CV AI
    """

    BASE_URL = (
        "https://jsearch-mega.p.rapidapi.com/search"
    )

    RAPIDAPI_HOST = (
        "jsearch-mega.p.rapidapi.com"
    )

    def __init__(
        self,
        api_key: Optional[str] = None,
        timeout: int = 20
    ):
        """
        Initialise le client JSearch.

        Priorité :

        1. api_key fournie directement
        2. variable d'environnement RAPIDAPI_KEY

        Args:
            api_key:
                Clé RapidAPI.

            timeout:
                Timeout HTTP en secondes.
        """

        # ----------------------------------------------------
        # RÉCUPÉRATION DE LA CLÉ
        # ----------------------------------------------------

        self.api_key = (
            api_key
            or os.getenv("RAPIDAPI_KEY")
        )

        self.timeout = timeout

        # ----------------------------------------------------
        # VALIDATION
        # ----------------------------------------------------

        if not self.api_key:

            raise ValueError(
                " RAPIDAPI_KEY introuvable.\n"
                "Configure ta clé RapidAPI avant "
                "d'utiliser JSearch."
            )

        # ----------------------------------------------------
        # HEADERS RAPIDAPI
        # ----------------------------------------------------

        self.headers = {

            "X-RapidAPI-Key":
                self.api_key,

            "X-RapidAPI-Host":
                self.RAPIDAPI_HOST
        }

        logger.info(
            " JSearchClient initialized"
        )

        logger.info(
            " RapidAPI authentication configured"
        )

    # ========================================================
    # SEARCH JOBS
    # ========================================================

    def search_jobs(
        self,
        query: str,
        location: str,
        page: int = 1,
        num_pages: int = 1,
        country: str = "ci",
        date_posted: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Recherche des offres réelles avec JSearch.
        """

        # ----------------------------------------------------
        # VALIDATION
        # ----------------------------------------------------

        if not query or not query.strip():

            raise ValueError(
                "query ne peut pas être vide."
            )

        if not location or not location.strip():

            raise ValueError(
                " location ne peut pas être vide."
            )

        logger.info(
            f" Searching JSearch | "
            f"Query='{query}' | "
            f"Location='{location}'"
        )

        # ----------------------------------------------------
        # PARAMÈTRES JSEARCH
        # ----------------------------------------------------

        params = {

            "query":
                f"{query} in {location}",

            "page":
                page,

            "num_pages":
                num_pages,

            "country":
                country
        }

        if date_posted:

            params["date_posted"] = (
                date_posted
            )

        try:

            response = requests.get(

                self.BASE_URL,

                headers=self.headers,

                params=params,

                timeout=self.timeout
            )

            logger.info(
                f" HTTP Status: "
                f"{response.status_code}"
            )

            if response.status_code == 401:

                logger.error(
                    "❌ 401 Unauthorized"
                )

                raise ValueError(
                    "Clé RapidAPI invalide "
                    "ou non autorisée."
                )

            if response.status_code == 403:

                logger.error(
                    "❌ 403 Forbidden"
                )

                raise PermissionError(
                    "Accès JSearch refusé. "
                    "Vérifie ton abonnement RapidAPI."
                )

            if response.status_code == 429:

                logger.error(
                    "❌ 429 Too Many Requests"
                )

                raise RuntimeError(
                    "Limite de requêtes RapidAPI dépassée."
                )

            response.raise_for_status()

            data = response.json()

            jobs = data.get(
                "data",
                []
            )

            if not isinstance(
                jobs,
                list
            ):

                logger.warning(
                    " Format JSearch inattendu."
                )

                return []

            logger.info(
                f" {len(jobs)} offres "
                f"récupérées depuis JSearch"
            )

            return jobs

        except requests.Timeout:

            logger.error(
                " Timeout JSearch."
            )

            raise RuntimeError(
                "Timeout lors de la connexion "
                "à JSearch."
            )

        except requests.ConnectionError:

            logger.error(
                "❌ Connection error JSearch."
            )

            raise RuntimeError(
                "Impossible de se connecter "
                "à JSearch."
            )

        except requests.RequestException as e:

            logger.error(
                f"❌ HTTP Error JSearch: {e}"
            )

            raise RuntimeError(
                f"Erreur API JSearch : {e}"
            )

        except (
            ValueError,
            PermissionError,
            RuntimeError
        ):

            raise

        except Exception as e:

            logger.exception(
                f"❌ Unexpected JSearch error: {e}"
            )

            raise RuntimeError(
                f"Erreur inattendue JSearch : {e}"
            )

    # ========================================================
    # SIMPLIFY JOBS
    # ========================================================

    def simplify_jobs(
        self,
        raw_jobs: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Convertit les données JSearch vers
        le format SCORE CV AI.
        """

        logger.info(
            " Simplifying JSearch jobs..."
        )

        simplified = []

        for job in raw_jobs:

            if not isinstance(
                job,
                dict
            ):

                continue

            job_id = (
                job.get("job_id")
                or "unknown"
            )

            title = (
                job.get("job_title")
                or "No title"
            )

            company = (
                job.get("employer_name")
                or "Unknown"
            )

            description = (
                job.get("job_description")
                or ""
            )

            # Location avec fallback pour assurer la compatibilité JSearch
            location = (
                job.get("job_location")
                or job.get("job_city")
                or job.get("job_country")
                or ""
            )

            apply_link = (
                job.get("job_apply_link")
                or job.get("job_google_link")
                or ""
            )

            employment_type = (
                job.get("job_employment_type")
                or ""
            )

            remote = bool(
                job.get(
                    "job_is_remote",
                    False
                )
            )

            min_salary = job.get(
                "job_min_salary"
            )

            max_salary = job.get(
                "job_max_salary"
            )

            salary_period = job.get(
                "job_salary_period"
            )

            posted_at = (
                job.get("job_posted_at_datetime_utc")
                or ""
            )

            simplified.append({

                "job_id":
                    job_id,

                "title":
                    title,

                "description":
                    description,

                "company":
                    company,

                "location":
                    location,

                "apply_link":
                    apply_link,

                "employment_type":
                    employment_type,

                "remote":
                    remote,

                "min_salary":
                    min_salary,

                "max_salary":
                    max_salary,

                "salary_period":
                    salary_period,

                "posted_at":
                    posted_at
            })

        logger.info(
            f" {len(simplified)} jobs simplified"
        )

        return simplified

# ============================================================
# ÉTAPE 4 : CV SCORING ENGINE
# ============================================================

class CVScoringEngine:
    """
    Calcule les 4 scores du modèle SCORE CV AI.

    1. TF-IDF     = 40%
    2. Entity     = 20%
    3. Skill      = 25%
    4. Relation   = 15%
    """

    TFIDF_WEIGHT = 0.40

    ENTITY_WEIGHT = 0.20

    SKILL_WEIGHT = 0.25

    RELATION_WEIGHT = 0.15

    def __init__(self):
        """
        Initialise le scoring engine.
        """

        logger.info(
            " CVScoringEngine initialized"
        )

        logger.info(
            f"Weights | "
            f"TF-IDF={self.TFIDF_WEIGHT} | "
            f"Entity={self.ENTITY_WEIGHT} | "
            f"Skill={self.SKILL_WEIGHT} | "
            f"Relation={self.RELATION_WEIGHT}"
        )

    @staticmethod
    def _normalize_score(
        score: float
    ) -> float:
        """
        Force un score entre 0 et 1.
        """

        try:

            score = float(score)

        except (
            ValueError,
            TypeError
        ):

            score = 0.0

        return round(
            float(
                np.clip(
                    score,
                    0.0,
                    1.0
                )
            ),
            3
        )

    # ========================================================
    # ENTITY SCORE
    # ========================================================

    def calculate_entity_score(
        self,
        entities: List[Dict[str, Any]],
        job_text: str
    ) -> float:

        if not entities or not job_text:

            return 0.0

        job_text_lower = (
            str(job_text).lower()
        )

        valid_entities = []

        for entity in entities:

            if not isinstance(
                entity,
                dict
            ):

                continue

            text = (
                entity.get("text")
                or ""
            )

            if text:

                valid_entities.append(
                    str(text).lower()
                )

        if not valid_entities:

            return 0.0

        matched = sum(

            1

            for entity_text
            in valid_entities

            if entity_text
            in job_text_lower
        )

        score = (
            matched
            /
            len(valid_entities)
        )

        score = self._normalize_score(
            score
        )

        logger.info(
            f"   Entity Score: {score:.3f}"
        )

        return score

    # ========================================================
    # SKILL SCORE
    # ========================================================

    def calculate_skill_score(
        self,
        skills: List[str],
        job_text: str
    ) -> float:

        if not skills or not job_text:

            return 0.0

        job_text_lower = (
            str(job_text).lower()
        )

        valid_skills = [

            str(skill).strip().lower()

            for skill in skills

            if skill
            and str(skill).strip()
        ]

        if not valid_skills:

            return 0.0

        matched = sum(

            1

            for skill
            in valid_skills

            if skill
            in job_text_lower
        )

        score = (
            matched
            /
            len(valid_skills)
        )

        score = self._normalize_score(
            score
        )

        logger.info(
            f"   Skill Score: {score:.3f}"
        )

        return score

    # ========================================================
    # RELATION SCORE
    # ========================================================

    def calculate_relation_score(
        self,
        relationships: List[Dict[str, Any]],
        job_text: str
    ) -> float:

        if not relationships or not job_text:

            return 0.0

        job_text_lower = (
            str(job_text).lower()
        )

        valid_relationships = [

            rel

            for rel in relationships

            if isinstance(
                rel,
                dict
            )
        ]

        if not valid_relationships:

            return 0.0

        matched = 0

        for relation in valid_relationships:

            source = str(
                relation.get(
                    "source",
                    ""
                )
            ).lower().strip()

            target = str(
                relation.get(
                    "target",
                    ""
                )
            ).lower().strip()

            source_match = (
                bool(source)
                and source
                in job_text_lower
            )

            target_match = (
                bool(target)
                and target
                in job_text_lower
            )

            if (
                source_match
                or target_match
            ):

                matched += 1

        score = (
            matched
            /
            len(valid_relationships)
        )

        score = self._normalize_score(
            score
        )

        logger.info(
            f"   Relation Score: {score:.3f}"
        )

        return score

    # ========================================================
    # FINAL SCORE
    # ========================================================

    def calculate_final_score(
        self,
        tfidf_score: float,
        entity_score: float,
        skill_score: float,
        relation_score: float
    ) -> float:

        tfidf_score = (
            self._normalize_score(
                tfidf_score
            )
        )

        entity_score = (
            self._normalize_score(
                entity_score
            )
        )

        skill_score = (
            self._normalize_score(
                skill_score
            )
        )

        relation_score = (
            self._normalize_score(
                relation_score
            )
        )

        final_score = (

            self.TFIDF_WEIGHT
            * tfidf_score

            +

            self.ENTITY_WEIGHT
            * entity_score

            +

            self.SKILL_WEIGHT
            * skill_score

            +

            self.RELATION_WEIGHT
            * relation_score
        )

        final_score = (
            self._normalize_score(
                final_score
            )
        )

        logger.info(
            f"   Final Score: "
            f"{final_score:.3f}"
        )

        return final_score

# ============================================================
# ÉTAPE 5 : SCORE CV AI MODEL
# ============================================================

class ScoreCVAIModel:
    """
    Pipeline principal SCORE CV AI.
    """

    def __init__(
        self,
        top_k: int = 10,
        jsearch_api_key: Optional[str] = None
    ):

        logger.info(
            "\n"
            + "=" * 70
        )

        logger.info(
            "🚀 INITIALIZING SCORE CV AI"
        )

        logger.info(
            "=" * 70
        )

        self.integrator = (
            CVDataIntegrator()
        )

        self.matcher = (
            TfidfMatcher()
        )

        self.scorer = (
            CVScoringEngine()
        )

        self.jsearch = (
            JSearchClient(
                api_key=jsearch_api_key
            )
        )

        self.top_k = max(
            1,
            int(top_k)
        )

        logger.info(
            f" Pipeline initialized | "
            f"Top K = {self.top_k}"
        )

    # ========================================================
    # RUN PIPELINE
    # ========================================================

    def run(
        self,
        cleaned_text: str,
        entities: List[Dict[str, Any]],
        relationships: List[Dict[str, Any]],
        search_query: str,
        location: str = "Abidjan, Côte d'Ivoire",
        country: str = "ci",
        date_posted: Optional[str] = None
    ) -> Dict[str, Any]:

        logger.info(
            "\n"
            + "=" * 70
        )

        logger.info(
            " EXECUTING SCORE CV AI PIPELINE"
        )

        logger.info(
            "=" * 70
        )

        # ----------------------------------------------------
        # ÉTAPE 1 : DATA INTEGRATION
        # ----------------------------------------------------

        logger.info(
            "\n[ÉTAPE 1] Data Integration..."
        )

        profile = (
            self.integrator.integrate(
                cleaned_text,
                entities,
                relationships
            )
        )

        cv_matching_text = (
            self.integrator.build_matching_text(
                profile
            )
        )

        # ----------------------------------------------------
        # ÉTAPE 2 : JSEARCH API
        # ----------------------------------------------------

        logger.info(
            "\n[ÉTAPE 2] JSearch API..."
        )

        raw_jobs = (
            self.jsearch.search_jobs(

                query=search_query,

                location=location,

                page=1,

                num_pages=1,

                country=country,

                date_posted=date_posted
            )
        )

        jobs = (
            self.jsearch.simplify_jobs(
                raw_jobs
            )
        )

        if not jobs:

            logger.warning(
                " No jobs found."
            )

            return {

                "status":
                    "success",

                "message":
                    "No jobs found",

                "results":
                    [],

                "total_jobs_scored":
                    0
            }

        # ----------------------------------------------------
        # ÉTAPE 3 : MATCHING & SCORING
        # ----------------------------------------------------

        logger.info(
            f"\n[ÉTAPE 3] "
            f"Scoring {len(jobs)} jobs..."
        )

        ranked_jobs = []

        for index, job in enumerate(
            jobs,
            start=1
        ):

            logger.info(
                "\n"
                + "-" * 60
            )

            logger.info(
                f" JOB {index}/{len(jobs)}"
            )

            logger.info(
                f"Title: {job['title']}"
            )

            logger.info(
                f"Company: {job['company']}"
            )

            job_text = " ".join(

                [

                    str(
                        job.get(
                            "title",
                            ""
                        )
                    ),

                    str(
                        job.get(
                            "description",
                            ""
                        )
                    ),

                    str(
                        job.get(
                            "company",
                            ""
                        )
                    ),

                    str(
                        job.get(
                            "location",
                            ""
                        )
                    )
                ]
            )

            tfidf_score = (
                self.matcher.calculate_similarity(

                    cv_matching_text,

                    job_text
                )
            )

            entity_score = (
                self.scorer.calculate_entity_score(

                    entities,

                    job_text
                )
            )

            skill_score = (
                self.scorer.calculate_skill_score(

                    profile[
                        "skills"
                    ],

                    job_text
                )
            )

            relation_score = (
                self.scorer.calculate_relation_score(

                    relationships,

                    job_text
                )
            )

            final_score = (
                self.scorer.calculate_final_score(

                    tfidf_score,

                    entity_score,

                    skill_score,

                    relation_score
                )
            )

            ranked_jobs.append({

                "job":
                    job,

                "scores": {

                    "tfidf":
                        tfidf_score,

                    "entity":
                        entity_score,

                    "skill":
                        skill_score,

                    "relation":
                        relation_score,

                    "final":
                        final_score
                }
            })

        # ----------------------------------------------------
        # ÉTAPE 4 : RANKING
        # ----------------------------------------------------

        logger.info(
            "\n[ÉTAPE 4] Ranking jobs..."
        )

        ranked_jobs = sorted(

            ranked_jobs,

            key=lambda x:
                x["scores"]["final"],

            reverse=True
        )

        top_jobs = (
            ranked_jobs[
                :self.top_k
            ]
        )

        result = {

            "status":
                "success",

            "cv_id":
                "cv_001",

            "search_query":
                search_query,

            "location":
                location,

            "country":
                country,

            "total_jobs_scored":
                len(ranked_jobs),

            "top_k":
                self.top_k,

            "results":
                top_jobs,

            "timestamp":
                datetime.now().isoformat()
        }

        logger.info(
            "\n"
            + "=" * 70
        )

        logger.info(
            " SCORE CV AI PIPELINE COMPLETED"
        )

        logger.info(
            "=" * 70
        )

        return result


# ============================================================
# FONCTION SAUVEGARDE JSON
# ============================================================

def save_results_json(
    results: Dict[str, Any],
    filename: str = "score_cv_ai_results.json"
) -> str:

    try:

        with open(
            filename,
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(

                results,

                file,

                indent=2,

                ensure_ascii=False,

                default=str
            )

        logger.info(
            f" JSON saved: {filename}"
        )

        return filename

    except Exception as e:

        logger.error(
            f"❌ JSON save error: {e}"
        )

        raise


# ============================================================
# AFFICHAGE DES RÉSULTATS
# ============================================================

def display_results(
    results: Dict[str, Any]
):

    print(
        "\n"
        + "=" * 70
    )

    print(
        " SCORE CV AI - TOP JOB MATCHES"
    )

    print(
        "=" * 70
    )

    if not results.get(
        "results"
    ):

        print(
            "⚠️ Aucun résultat."
        )

        return

    for index, result in enumerate(

        results["results"],

        start=1
    ):

        job = result["job"]

        scores = result["scores"]

        print(
            f"\n{index}. "
            f"{job['title']}"
        )

        print(
            f"    Company : "
            f"{job['company']}"
        )

        print(
            f"    Location : "
            f"{job.get('location', 'N/A')}"
        )

        print(
            f"    Type : "
            f"{job.get('employment_type', 'N/A')}"
        )

        print(
            f"    Remote : "
            f"{job.get('remote', False)}"
        )

        print(
            f"    Final Score : "
            f"{scores['final']:.3f} "
            f"({scores['final'] * 100:.1f}%)"
        )

        print(
            "    Breakdown :"
        )

        print(
            f"      TF-IDF   : "
            f"{scores['tfidf']:.3f}"
        )

        print(
            f"      Entity   : "
            f"{scores['entity']:.3f}"
        )

        print(
            f"      Skill    : "
            f"{scores['skill']:.3f}"
        )

        print(
            f"      Relation : "
            f"{scores['relation']:.3f}"
        )

        if job.get(
            "apply_link"
        ):

            print(
                f"   Apply : "
                f"{job['apply_link']}"
            )

# ============================================================
# TEST COMPLET
# ============================================================

if __name__ == "__main__":

    print(
        "\n"
        + "=" * 70
    )

    print(
        "🚀 SCORE CV AI - SECTION 5"
    )

    print(
        "DATA INTEGRATION & MODEL BUILDING"
    )

    print(
        "=" * 70
    )

    if not os.getenv(
        "RAPIDAPI_KEY"
    ):

        print(
            "\n"
            "❌ ERREUR : RAPIDAPI_KEY n'est pas configurée.\n"
        )

        print(
            "Dans une cellule Colab, exécute :\n"
        )

        print(
            'os.environ["RAPIDAPI_KEY"] = '
            '"TA_CLE_RAPIDAPI"'
        )

        print(
            "\nPuis relance cette cellule."
        )

    else:

        test_cv_text = """

        Lionel KOUAKOU est Data Scientist
        chez Intelcia.

        Compétences :
        Python, Machine Learning,
        TensorFlow, SQL, Power BI, AWS.

        Formation :
        Licence Informatique,
        Data Science.

        Certifications :
        NVIDIA Machine Learning,
        AWS Certification.

        Expérience :
        3 ans en Data Science
        et Machine Learning.
        """

        test_entities = [

            {
                "text":
                    "Lionel KOUAKOU",

                "label":
                    "PERSON"
            },

            {
                "text":
                    "Data Scientist",

                "label":
                    "JOB_TITLE"
            },

            {
                "text":
                    "Intelcia",

                "label":
                    "COMPANY"
            },

            {
                "text":
                    "Python",

                "label":
                    "SKILL"
            },

            {
                "text":
                    "Machine Learning",

                "label":
                    "SKILL"
            },

            {
                "text":
                    "TensorFlow",

                "label":
                    "SKILL"
            },

            {
                "text":
                    "SQL",

                "label":
                    "SKILL"
            },

            {
                "text":
                    "Power BI",

                "label":
                    "SKILL"
            }
        ]

        test_relationships = [

            {
                "relation":
                    "PERSON_HAS_JOB",

                "source":
                    "Lionel",

                "target":
                    "Data Scientist"
            },

            {
                "relation":
                    "PERSON_WORKS_AT",

                "source":
                    "Lionel",

                "target":
                    "Intelcia"
            },

            {
                "relation":
                    "PERSON_HAS_SKILL",

                "source":
                    "Lionel",

                "target":
                    "Python"
            },

            {
                "relation":
                    "SKILL_IN_JOB",

                "source":
                    "Python",

                "target":
                    "Data Scientist"
            }
        ]

        model = ScoreCVAIModel(

            top_k=10,

            jsearch_api_key=
                os.getenv(
                    "RAPIDAPI_KEY"
                )
        )

        results = model.run(

            cleaned_text=
                test_cv_text,

            entities=
                test_entities,

            relationships=
                test_relationships,

            search_query=
                "Data Scientist",

            location=
                "Abidjan, Côte d'Ivoire",

            country=
                "ci",

            date_posted=
                "month"
        )

        display_results(
            results
        )

        print(
            "\n"
            + "=" * 70
        )

        print(
            "💾 SAUVEGARDE"
        )

        print(
            "=" * 70
        )

        output_file = (
            save_results_json(
                results,
                "score_cv_ai_results.json"
            )
        )

        print(
            f"✅ Fichier créé : "
            f"{output_file}"
        )

        print(
            "\n"
            + "=" * 70
        )

        print(
            "✅ SECTION 5 TERMINÉE"
        )

        print(
            "Data Integration & Model Building"
        )

        print(
            "=" * 70
        )